version: '2.0'

services:

  varnish4:
    image: eeacms/varnish:4.1-3.1
    container_name: varnish4

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
    - php71
    - php56

    environment:
      TZ: "Europe/Bucharest"

  php71:
    build: image-php71
    container_name: php71
    depends_on:
    - db

#  php72:
#    build: image-php72
#    container_name: php72
#    depends_on:
#    - db

  php56:
    build: image-php56
    container_name: php56
    depends_on:
    - db

  db:
    image: mariadb
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
    - ./conf-mysqld/server.cnf:/etc/mysql/conf.d/server.cnf
    - ./conf-mysqld/client.cnf:/etc/mysql/conf.d/client.cnf

  mail:
    image: eaudeweb/mailtrap
    container_name: mailtrap
