version: '2.0'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
    - php7
    - php56

    environment:
      TZ: "Europe/Bucharest"

  php7:
    build: image-php7
    container_name: php7
    depends_on:
    - db

  php56:
    build: image-php56
    container_name: php56
    depends_on:
    - db

  db:
    image: mariadb
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
    - ./conf-mysqld/server.cnf:/etc/mysql/conf.d/server.cnf
    - ./conf-mysqld/client.cnf:/etc/mysql/conf.d/client.cnf

  mail:
    image: eaudeweb/mailtrap
    container_name: mailtrap
